name: HardcoreScores
author: Marc Towler
version: 0.4

main: uk.co.marctowler.HardcoreScores.core

description: Hardcore Scoreboards
commands:
   topkills:
       usage: /<command>
       description: Shows the top 10 kills